[project]
name = "tennis_web_backend"
version = "0.1.0"
description = "Backend for a Tennis web application"
authors = [
    { name = "Valentine", email = "vchidubem9@gmail.com" }
]

requires-python = ">=3.10"
readme = "README.md"


[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
]
# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Same as Python 3.10
target-version = "py310"
line-length = 120

# rules
select = [
    "E", # pycodestyle
    "F", # pyflakes
    "W", # pycodestyle warnings
    "I", # isort
    "UP", # pyupgrade
    "C4", # flake8-comprehensions
    "B",  # flake8-bugbear
    "RUF",# ruff specific
]
ignore = [
     "E501", # Line too long
     "E731", # do not assign a lambda expression, use a def
]

[tool.ruff.isort]
known-first-party = ["app"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
required-imports = ["from __future__ import annotations"]

[tool.ruff.lint.per-file-ignores]
"test/**/*" = ["S101", "ANN"] # ignore all assertion rules in tests

[tool.mypy]
# Use type checking for files in app
files = ["app/**/*.py"]
# Check dynamically typed code
check_untyped_defs = true
# Raise errors for any errors
strict = true
# Type checking with debug
show_error_codes = true
show_column_numbers = true

[[tool.mypy.overrides]]
module = ["*"]
ignore_missing_imports = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
